# Rutinas para obtener los datos estadísticos de la obtención de armónicos esféricos mediante un procesador cuántico real en formato LAtex.

In [2]:
import numpy as np
nCubits = 4
formatoNumero = '{:.8f}'
precision = 8
calculado = {}
real = {}
error = {}

# Fc5

In [3]:
calculado['Fc5'] = [(0.28209479177387814+0j),
  (0.3372090235898002+0j),
  (0.005184744327578965+0.04051216891255327j),
  (-0.005184744327578965+0.04051216891255327j),
  (0.27393334400007624+0j),
  (0.007708833695814011+0.06166353836050299j),
  (-0.007708833695814011+0.06166353836050299j),
  (-0.01181525872293482-0.010644654753703542j),
  (-0.01181525872293482+0.010644654753703542j),
  (0.3016384296325903+0j),
  (0.014192134605188816+0.11808128917182575j),
  (-0.014192134605188814+0.11808128917182573j),
  (-0.09868806841119898-0.09328658901231568j),
  (-0.09868806841119897+0.09328658901231567j),
  (0.008245519326166458-0.0011440611023069843j),
  (-0.00824551932616646-0.0011440611023069845j),
  (0.3668907230886574+0j),
  (0.014518198935219816+0.10357300359977431j),
  (-0.014518198935219818+0.10357300359977432j),
  (-0.4987684360586026-0.46824722520469164j),
  (-0.4987684360586027+0.4682472252046917j),
  (0.01691804652222282-0.001848615561265337j),
  (-0.01691804652222282-0.001848615561265337j),
  (-0.011311741888682402+0.04557338851933088j),
  (-0.0113117418886824-0.045573388519330876j)]

real['Fc5'] =  [ 0.28209479+0.j        ,  0.45614974+0.j        ,
        -0.04030991+0.11706847j,  0.04030991+0.11706847j,
         0.5092682 +0.j        , -0.08414891+0.24438619j,
         0.08414891+0.24438619j, -0.03909185-0.0305419j ,
        -0.03909185+0.0305419j ,  0.47306573+0.j        ,
        -0.1266131 +0.36771115j,  0.1266131 +0.36771115j,
        -0.0965577 -0.07543915j, -0.0965577 +0.07543915j,
         0.01610453-0.0104584j , -0.01610453-0.0104584j ,
         0.3639207 +0.j        , -0.15979636+0.46408233j,
         0.15979636+0.46408233j, -0.1726922 -0.13492193j,
        -0.1726922 +0.13492193j,  0.04510461-0.02929128j,
        -0.04510461-0.02929128j,  0.00176578+0.00708217j,
         0.00176578-0.00708217j]

# Cz

In [4]:
calculado['Cz'] = [(0.28209479177387814+0j),
  (0.4867458223576888+0j),
  (-0.023903389319797273-0.0012693126832134857j),
  (0.023903389319797273-0.0012693126832134857j),
  (0.6146981606771615+0j),
  (-0.053246494918744655-0.0028274840204794115j),
  (0.05324649491874466-0.0028274840204794115j),
  (0.0015551804961365756+9.276954372889938e-05j),
  (0.0015551804961365756-9.276954372889938e-05j),
  (0.6942572491506507+0j),
  (-0.11865544623922013-0.006300816207643786j),
  (0.11865544623922011-0.006300816207643785j),
  (0.02682123212002941+0.0015999387030658314j),
  (0.026821232120029403-0.001599938703065831j),
  (0.0075302057695009975+0.0003816596649063257j),
  (-0.007530205769500998+0.00038165966490632576j),
  (0.7395467584841933+0j),
  (-0.19007655493625047-0.010093404693964707j),
  (0.19007655493625047-0.010093404693964707j),
  (0.10107844620122189+0.006029526063507146j),
  (0.1010784462012219-0.006029526063507147j),
  (0.022504772962730683+0.0011406280745390452j),
  (-0.02250477296273068+0.001140628074539045j),
  (-0.0020789079559334284-8.933628728733131e-05j),
  (-0.0020789079559334284+8.933628728733131e-05j)]

real['Cz'] = [0.28209479+0.j,  0.48860251+0.j, -0.        +0.j,  0.        +0.j,
         0.63078313+0.j, -0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.74635267+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j, -0.        +0.j,  0.        +0.j,
         0.84628438+0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j, -0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j]

# C2

In [5]:
calculado['C2'] = [(0.28209479177387814+0j),
  (0.4860862089666199+0j),
  (-0.01056814088122096+0.0006912301448473009j),
  (0.01056814088122096+0.0006912301448473009j),
  (0.6112446230376465+0j),
  (-0.02350938133696264+0.0015376775583769162j),
  (0.02350938133696264+0.0015376775583769162j),
  (-0.00017196927474072253-0.00018651249844689553j),
  (-0.00017196927474072253+0.00018651249844689553j),
  (0.6846666174030848+0j),
  (-0.044345078472771624+0.0029004775163876772j),
  (0.044345078472771624+0.0029004775163876772j),
  (0.009403083971567342+0.01019829087078008j),
  (0.009403083971567342-0.01019829087078008j),
  (-0.0001576104716155209+0.0013105500968894142j),
  (0.00015761047161552092+0.0013105500968894144j),
  (0.720584699199643+0j),
  (-0.06737793789609611+0.004406987217041168j),
  (0.06737793789609611+0.004406987217041168j),
  (0.04143225939776612+0.04493613308672815j),
  (0.041432259397766125-0.04493613308672816j),
  (-0.000470396333060103+0.003911402291671302j),
  (0.000470396333060103+0.003911402291671302j),
  (0.0007765563687024568-0.0014974111474068633j),
  (0.0007765563687024567+0.0014974111474068631j)]

real['C2'] = [ 0.28209479+0.j,  0.48860251+0.j, -0.        +0.j,  0.        +0.j,
         0.63078313+0.j, -0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.74635267+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j, -0.        +0.j,  0.        +0.j,
         0.84628438+0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j, -0.        +0.j,  0.        +0.j, -0.        +0.j,
         0.        -0.j]

# C6

In [6]:
calculado['C6'] = [(0.28209479177387814+0j),
  (0.48640380059935673+0j),
  (0.0010424214928434184-0.009933388664987736j),
  (-0.0010424214928434184-0.009933388664987736j),
  (0.6108188444245556+0j),
  (0.002320436155268272-0.022111779506480182j),
  (-0.002320436155268272-0.022111779506480182j),
  (-0.00016451418264167426+4.870917687512356e-05j),
  (-0.0001645141826416743-4.870917687512357e-05j),
  (0.6817931596421408+0j),
  (0.0023977416537815416-0.022848435041640264j),
  (-0.0023977416537815416-0.022848435041640264j),
  (-0.02855329310548853+0.008454027378732342j),
  (-0.02855329310548853-0.008454027378732342j),
  (0.005119140220777155+0.0041935542014772415j),
  (-0.0051191402207771556+0.0041935542014772415j),
  (0.7166441875770516+0j),
  (0.002618241724104653-0.02494961284180444j),
  (-0.002618241724104653-0.02494961284180444j),
  (-0.1410772215283096+0.04176998740248847j),
  (-0.1410772215283096-0.041769987402488475j),
  (0.01528831226935097+0.012524049622711779j),
  (-0.01528831226935097+0.012524049622711779j),
  (-0.0009568707395660876-0.0026034508069423022j),
  (-0.0009568707395660876+0.0026034508069423022j)]
real['C6'] = [ 0.28209479+0.j,  0.48860251+0.j, -0.        +0.j,  0.        +0.j,
         0.63078313+0.j, -0.        +0.j,  0.        +0.j, -0.        +0.j,
         0.        -0.j,  0.74635267+0.j,  0.        +0.j,  0.        +0.j,
        -0.        +0.j,  0.        -0.j,  0.        +0.j, -0.        +0.j,
         0.84628438+0.j,  0.        +0.j,  0.        +0.j, -0.        +0.j,
         0.        -0.j,  0.        +0.j, -0.        +0.j,  0.        +0.j,
         0.        +0.j]

# Fc4

In [7]:
calculado['Fc4'] = [(0.28209479177387814+0j),
  (0.30364203102206955+0j),
  (-0.017979066396093986-0.029786327226806134j),
  (0.017979066396093986-0.029786327226806134j),
  (0.17496347082383545+0j),
  (-0.02498379057408074-0.04139121270319343j),
  (0.02498379057408074-0.04139121270319343j),
  (-0.015214537367353223+0.022685093954078778j),
  (-0.015214537367353221-0.022685093954078774j),
  (0.15669674205458947+0j),
  (-0.042561957661336525-0.07051336094901257j),
  (0.04256195766133652-0.07051336094901257j),
  (-0.08424397975799586+0.12560898499459966j),
  (-0.08424397975799586-0.12560898499459966j),
  (0.023219903484973606-0.0018657414945210853j),
  (-0.02321990348497361-0.0018657414945210855j),
  (0.2723184441464647+0j),
  (-0.02972761758139241-0.04925041853925643j),
  (0.029727617581392415-0.04925041853925643j),
  (-0.2682729717043764+0.39999885777088234j),
  (-0.2682729717043765-0.3999988577708824j),
  (0.04329002706221054-0.003478395155310385j),
  (-0.04329002706221054-0.003478395155310385j),
  (-0.0536143845541332-0.042158872644329264j),
  (-0.053614384554133185+0.04215887264432926j)]
real['Fc4'] = [ 0.28209479+0.j        ,  0.43141041+0.j        ,
        -0.10425994-0.12425216j,  0.10425994-0.12425216j,
         0.42224287+0.j        , -0.20584362-0.24531488j,
         0.20584362-0.24531488j, -0.01478375+0.08384279j,
        -0.01478375-0.08384279j,  0.29588079+0.j        ,
        -0.28262933-0.33682452j,  0.28262933-0.33682452j,
        -0.03453572+0.19586178j, -0.03453572-0.19586178j,
         0.0373876 -0.02158574j, -0.0373876 -0.02158574j,
         0.09352272+0.j        , -0.3097342 -0.36912685j,
         0.3097342 -0.36912685j, -0.05706566+0.32363544j,
        -0.05706566-0.32363544j,  0.09903388-0.05717724j,
        -0.09903388-0.05717724j, -0.02020079-0.00735249j,
        -0.02020079+0.00735249j]

# F2

In [8]:
calculado['F2'] = [(0.28209479177387814+0j),
  (0.07116495585866028+0j),
  (-0.058005107765633626-0.09062274400012062j),
  (0.058005107765633626-0.09062274400012062j),
  (-0.28090349759215694-0j),
  (-0.01889129496749687-0.029514314404645168j),
  (0.01889129496749687-0.029514314404645168j),
  (-0.11898983076812038+0.1727863509034086j),
  (-0.11898983076812039-0.17278635090340863j),
  (-0.11034824154689715-0j),
  (-0.0003805527462990188-0.0005945465052102056j),
  (0.0003805527462990188-0.0005945465052102056j),
  (-0.06225819016087244+0.09040575503221698j),
  (-0.062258190160872424-0.09040575503221697j),
  (0.1865494059932478-0.014171165714740482j),
  (-0.18654940599324782-0.014171165714740483j),
  (0.6750440212526475+0j),
  (0.018396020712226728+0.028740535788000853j),
  (-0.018396020712226728+0.028740535788000853j),
  (0.4204294317145097-0.6105098801250398j),
  (0.4204294317145098+0.6105098801250399j),
  (0.08151276294874965-0.006192090859055855j),
  (-0.08151276294874965-0.006192090859055855j),
  (-0.19301467192069777-0.1447895058117461j),
  (-0.19301467192069774+0.1447895058117461j)]
real['F2'] = [ 0.28209479+0.j        ,  0.18303372+0.j        ,
        -0.2059084 -0.24539207j,  0.2059084 -0.24539207j,
        -0.18261478+0.j        , -0.1724783 -0.20555164j,
         0.1724783 -0.20555164j, -0.05766306+0.32702344j,
        -0.05766306-0.32702344j, -0.32129619+0.j        ,
         0.057465  +0.06848412j, -0.057465  +0.06848412j,
        -0.05715077+0.32411813j, -0.05715077-0.32411813j,
         0.2880032 -0.16627872j, -0.2880032 -0.16627872j,
        -0.05507875+0.j        ,  0.21311028+0.25397494j,
        -0.21311028+0.25397494j,  0.00088336-0.0050098j ,
         0.00088336+0.0050098j ,  0.32366369-0.18686732j,
        -0.32366369-0.18686732j, -0.30732268-0.11185631j,
        -0.30732268+0.11185631j]

# Cálculo del error

In [9]:
for x in calculado.keys():
    arrTmp = []
    for c,r in zip(calculado[x], real[x]):
        arrTmp.append(complex(abs(abs(c.real) - abs(r.real)), abs(abs(c.imag) - abs(r.imag))))
    error[x] = np.array(arrTmp)


## Tabla de errores

In [10]:

encabezadoFigura = "\\begin{figure}[h]\n\\centering"
pieFigura = "\\caption{Error obtenido en la evaluación de armónicos esféricos mediante computación cuántica.}\n\\end{figure}"
encabezadoSubfigura = "\\begin{subfigure}[t]{0.4\\textwidth}\n"
encabezadoSubfigura += "\\resizebox{\\textwidth}{!}{\n"
encabezadoSubfigura += "\\begin{tabular}{|c|p{2.1cm}|p{2.1cm}|}\n"
encabezadoSubfigura += "\\hline\n"
encabezadoSubfigura += "\\multicolumn{3}{|c|}{$"
encabezadoSubfigura2 = "$}\\\\\n"
encabezadoSubfigura2 += "\\hline\n"
encabezadoSubfigura2 += "Armónico Esférico & Error $\\mathbb{R}$ & Error $\\mathbb{I}$\\\\\n"
encabezadoSubfigura2 += "\\hline\\hline\n"
pieSubfigura = "\\hline\n\\end{tabular}}\n\\end{subfigure}\n"
print(encabezadoFigura)
for x in error.keys():
    print(encabezadoSubfigura + str(x) + encabezadoSubfigura2)
    i = 0
    for l in range(nCubits + 1):
        for m in range(l+1):
            if (l != 0):
                print("$Y_" + str(l) + "^{" + str(m) + "}$&$"+ formatoNumero.format(error[x][i].real) + "$&$" + formatoNumero.format(error[x][i].imag) +"$\\\\")
                if (m == 0):
                    i += 1
                else:
                    i += 2
            else:
                i +=1
    print(pieSubfigura)

print(pieFigura)

\begin{figure}[h]
\centering
\begin{subfigure}[t]{0.4\textwidth}
\resizebox{\textwidth}{!}{
\begin{tabular}{|c|p{2.1cm}|p{2.1cm}|}
\hline
\multicolumn{3}{|c|}{$Fc5$}\\
\hline
Armónico Esférico & Error $\mathbb{R}$ & Error $\mathbb{I}$\\
\hline\hline

$Y_1^{0}$&$0.11894072$&$0.00000000$\\
$Y_1^{1}$&$0.03512517$&$0.07655630$\\
$Y_2^{0}$&$0.23533486$&$0.00000000$\\
$Y_2^{1}$&$0.07644008$&$0.18272265$\\
$Y_2^{2}$&$0.02727659$&$0.01989725$\\
$Y_3^{0}$&$0.17142730$&$0.00000000$\\
$Y_3^{1}$&$0.11242097$&$0.24962986$\\
$Y_3^{2}$&$0.00213037$&$0.01784744$\\
$Y_3^{3}$&$0.00785901$&$0.00931434$\\
$Y_4^{0}$&$0.00297002$&$0.00000000$\\
$Y_4^{1}$&$0.14527816$&$0.36050933$\\
$Y_4^{2}$&$0.32607624$&$0.33332530$\\
$Y_4^{3}$&$0.02818656$&$0.02744266$\\
$Y_4^{4}$&$0.00954596$&$0.03849122$\\
\hline
\end{tabular}}
\end{subfigure}

\begin{subfigure}[t]{0.4\textwidth}
\resizebox{\textwidth}{!}{
\begin{tabular}{|c|p{2.1cm}|p{2.1cm}|}
\hline
\multicolumn{3}{|c|}{$Cz$}\\
\hline
Armónico Esférico & Error $\mathb

## Histograma de errores

In [11]:
encabezado = "\\newcommand{\\Y}[2]{$Y_{#1}^{#2}$}\n"
encabezado += "\\begin{figure}[h]\n"
encabezado += "\\centering\n"
encabezadoSubfigura = "\\begin{subfigure}[t]{1\\textwidth}\n"
encabezadoSubfigura += "\\resizebox{1\\textwidth}{0.4\\textheight}{\n"
encabezadoSubfigura += "\\begin{tikzpicture}\n"
encabezadoSubfigura += "\\centering\n"
encabezadoSubfigura += "\\begin{axis}[\n"
armonicosReal = "xticklabels={\\Y{1}{0}, \\Y{1}{1}, \\Y{2}{0}, \\Y{2}{1}, \\Y{2}{2}, \\Y{3}{0}, \\Y{3}{1}, \\Y{3}{2}, \\Y{3}{3}, \\Y{4}{0}, \\Y{4}{1}, \\Y{4}{2}, \\Y{4}{3}, \\Y{4}{4},},\n"
encabezadoSubfigura += armonicosReal
encabezadoSubfigura += "ylabel=Error,\n"
encabezadoSubfigura += "enlargelimits=0.01,\n"
encabezadoSubfigura += "legend style={at={(0.5,-0.1)},\n"
encabezadoSubfigura += "anchor=north,legend columns=-1},\n"
encabezadoSubfigura += "ybar interval=0.8,]\n"

encabezadoElectrodo = "\\addplot\n  coordinates {"
pieElectrodo = "};\n"

strListaElectrodos = (str(list(error.keys())).replace("'", "").replace("[", "").replace("]", ""))
pieSubfigura =     "\\legend{" + strListaElectrodos + "}\n"
pieSubfigura +=    "\\end{axis}\n"
pieSubfigura +=    "\\end{tikzpicture}\n"
pieSubfigura +=    "}\n"
pieSubfigura +=    "\\caption{Histograma de error de la parte xxxxxx en el circuito cuántico}\n"
pieSubfigura +=    "\\label{fig:erroresR}\n"
pieSubfigura +=    "\\end{subfigure}\n"
pie =     "\\caption{Errores en la evaluación de armónicos esféricos mediante computación cuántica.}\n"
pie += "\\end{figure}\n"
print(encabezado)
armonicosImaginaria = "xticklabels={ \\Y{1}{1}, \\Y{2}{1}, \\Y{2}{2}, \\Y{3}{1}, \\Y{3}{2}, \\Y{3}{3}, \\Y{4}{1}, \\Y{4}{2}, \\Y{4}{3}, \\Y{4}{4},},\n"
print(encabezadoSubfigura.replace(armonicosReal, armonicosImaginaria))
for x in error.keys():
    print(encabezadoElectrodo)
    i = 0
    j = 0
    for l in range(nCubits + 1):
        for m in range(l+1):
            if (l != 0):
                print("(" + str(j) + ", "  + str(error[x][i].real) + ")")
                j += 1
                if (m == 0):
                    i += 1
                else:
                    i += 2
            else:
                i +=1
    print("(" + str(j) +",0)")
    print(pieElectrodo)
print(pieSubfigura.replace("xxxxxx", "real"))
print(encabezadoSubfigura)
for x in error.keys():
    print(encabezadoElectrodo)
    i = 0
    j = 0
    for l in range(nCubits + 1):
        for m in range(l+1):
            if (l != 0 and m !=0):
                print("(" + str(j) + ", "  + str(error[x][i].imag) + ")")
                j += 1
                i += 2
            else:
                i +=1
    print("(" + str(j) +",0)")
    print(pieElectrodo)
print(pieSubfigura.replace("xxxxxx", "imaginaria").replace("fig:erroresR", "fig:erroresI"))
print(pie)

\newcommand{\Y}[2]{$Y_{#1}^{#2}$}
\begin{figure}[h]
\centering

\begin{subfigure}[t]{1\textwidth}
\resizebox{1\textwidth}{0.4\textheight}{
\begin{tikzpicture}
\centering
\begin{axis}[
xticklabels={ \Y{1}{1}, \Y{2}{1}, \Y{2}{2}, \Y{3}{1}, \Y{3}{2}, \Y{3}{3}, \Y{4}{1}, \Y{4}{2}, \Y{4}{3}, \Y{4}{4},},
ylabel=Error,
enlargelimits=0.01,
legend style={at={(0.5,-0.1)},
anchor=north,legend columns=-1},
ybar interval=0.8,]

\addplot
  coordinates {
(0, 0.11894071641019982)
(1, 0.035125165672421035)
(2, 0.2353348559999237)
(3, 0.07644007630418598)
(4, 0.02727659127706518)
(5, 0.17142730036740972)
(6, 0.1124209653948112)
(7, 0.002130368411198985)
(8, 0.00785901067383354)
(9, 0.002970023088657403)
(10, 0.14527816106478017)
(11, 0.3260762360586026)
(12, 0.028186563477777184)
(13, 0.009545961888682402)
(14,0)
};

\addplot
  coordinates {
(0, 0.0018566876423111722)
(1, 0.023903389319797273)
(2, 0.016084969322838427)
(3, 0.053246494918744655)
(4, 0.0015551804961365756)
(5, 0.05209542084934937)
(6, 0.1

## Estadísticas totales

In [58]:
arrTotal = []
cov_mat = [[],[]]
cov_matElecR = []
cov_matElecI = []
for x in error.keys():
    arrTotal.append(error[x])
    cov_mat = np.concatenate((cov_mat, np.stack((error[x].real, error[x].imag), axis = 0)), axis=1)
    cov_matElecR.append(error[x].real)
    cov_matElecI.append(error[x].imag)
arrTotal = np.array(arrTotal)
Etotal_max = np.max(arrTotal)
Etotal_mean = np.mean(arrTotal)
Etotal_median = np.median(arrTotal)
Etotal_std = np.std(arrTotal)

Etotal_covIR = np.cov(cov_mat)
Etotal_covElectrodoR = np.cov(cov_matElecR)
Etotal_covElectrodoI = np.cov(cov_matElecI)

print("Error total:")
print("Máximo = " + str(Etotal_max))
print("Media = " + str(Etotal_mean))
print("Mediana = " + str(Etotal_median))
print("Desviación típica = " + str(Etotal_std))
print("Covarianza entre parte real e imaginaria:")
print(Etotal_covIR)

print("Covarianza entre electrodos R:")
print(Etotal_covElectrodoR)

print("Covarianza entre electrodos I:")
print(Etotal_covElectrodoI)

Error total:
Máximo = (0.6199652712526476+0j)
Media = (0.07729710724226564+0.0633366301655637j)
Mediana = (0.03426938011327712+0.055681341865887996j)
Desviación típica = 0.14810111166202308
Covarianza entre parte real e imaginaria:
[[0.00992233 0.00672211]
 [0.00672211 0.01215882]]
Covarianza entre electrodos R:
[[0.00938843 0.00280261 0.00111221 0.00251219 0.00669783 0.00575396]
 [0.00280261 0.00333019 0.00142436 0.00078762 0.00471411 0.00345237]
 [0.00111221 0.00142436 0.00096933 0.00077918 0.00214516 0.00301316]
 [0.00251219 0.00078762 0.00077918 0.00200931 0.00131628 0.00527173]
 [0.00669783 0.00471411 0.00214516 0.00131628 0.00937372 0.00532885]
 [0.00575396 0.00345237 0.00301316 0.00527173 0.00532885 0.02068832]]
Covarianza entre electrodos I:
[[1.72649268e-02 3.97051123e-04 8.71155640e-04 1.52727002e-03
  1.09034467e-02 1.25111326e-02]
 [3.97051123e-04 1.00332782e-05 1.57978115e-05 3.29888725e-05
  2.82412478e-04 2.47489879e-04]
 [8.71155640e-04 1.57978115e-05 1.46947815e-04 1.1

## Estadísticas por electrodo

In [13]:

strListaElectrodosTituloTabla = (str(list(error.keys())).replace("'", "$").replace("[", "").replace("]", "").replace(",", " & "))
cabecera = "\\begin{figure}[h]\n"
cabecera += "\\centering\n"
cabecera += "\\begin{tabular}{|c|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|}\n"
cabecera += "\\hline\n"
cabecera += "& " + strListaElectrodosTituloTabla +"\\\\\n"
cabecera += "\\hline\n"
cabecera += "\\hline\n"
pie = "\\end{tabular}\n"
pie += "\\caption{Estadísticas de error por electrodo.}\n"
pie += "\\end{figure}\n"

print(cabecera)

E_max = {}
E_mean = {}
E_median = {}
E_std = {}
E_covIR = {}
#Calcular estadísticas
for x in error.keys():
        E_max[x] = max(error[x])
        E_mean[x] = np.mean(error[x])
        E_median[x] = np.median(error[x])
        E_std[x] = np.std(error[x])
        cov_mat = np.stack((error[x].real, error[x].imag), axis = 0)
        E_covIR[x] = np.cov(cov_mat)

strE_maxR = ("$E_{max\\mathbb{R}}$  & $" + np.array2string(np.array(list(E_max.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_meanR = ("$\\overline{E_{\\mathbb{R}}}$   & $" + np.array2string(np.array(list(E_mean.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_medianR = ("$\\tilde{E_{\\mathbb{R}}}$  & $" + np.array2string(np.array(list(E_median.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_stdR = ("$E_{\\sigma\\mathbb{R}}$  & $" + np.array2string(np.array(list(E_std.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_maxI = ("$E_{max\\mathbb{I}}$  & $" + np.array2string(np.array(list(E_max.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_meanI = ("$\\overline{E_{\\mathbb{I}}}$   & $" + np.array2string(np.array(list(E_mean.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_medianI = ("$\\tilde{E_{\\mathbb{I}}}$  & $" + np.array2string(np.array(list(E_median.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_stdI = ("$E_{\\sigma\\mathbb{I}}$  & $" + np.array2string(np.array(list(E_std.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")

print(strE_maxR)
print("\\hline")
print(strE_maxI)
print("\\hline")
print(strE_meanR)
print("\\hline")
print(strE_meanI)
print("\\hline")
print(strE_medianR)
print("\\hline\n")
print(strE_medianI)
print("\\hline\n")
print(strE_stdR)
print("\\hline\n")
print(strE_stdI)
print("\\hline\n")
print(pie)

cabeceraCov = "\\begin{figure}[h]\n"
cabeceraCov += "\\centering\n"
print(cabeceraCov)
for x in E_covIR.keys():
        print("\\begin{subfigure}[t]{0.4\\textwidth}")
        print("\\begin{tabular}{|p{2cm}|p{2cm}|}")
        print("\\hline")
        print("\\multicolumn{2}{|c|}{$" + x + "$}\\\\")
        print("\\hline")
        print("$\\mathbb{R}$& $\mathbb{I}$ \\\\")
        print("\\hline\n\\hline")
        strTablaTmp = np.array2string(E_covIR[x])
        strTablaTmp = strTablaTmp.replace("[[", "$")
        strTablaTmp = strTablaTmp.replace("]]", "$\\\\\n")
        strTablaTmp = strTablaTmp.replace("]", "$\\\\")
        strTablaTmp = strTablaTmp.replace("[", "$")
        print(strTablaTmp)
        print("\\hline")
        print("\\end{tabular}")
        print("\\end{subfigure}")
print("\\end{figure}")




\begin{figure}[h]
\centering
\begin{tabular}{|c|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|}
\hline
& $Fc5$ &  $Cz$ &  $C2$ &  $C6$ &  $Fc4$ &  $F2$\\
\hline
\hline

$E_{max\mathbb{R}}$  & $0.32607624$ & $0.19007655$ & $0.12569968$ & $0.14107722$ & $
 0.28000658$ & $0.61996527$\\

\hline
$E_{max\mathbb{I}}$  & $0.3333253 $ & $0.0100934 $ & $0.        $ & $0.04176999$ & $
 0.31987643$ & $0.        $\\

\hline
$\overline{E_{\mathbb{R}}}$   & $0.08277404$ & $0.05086704$ & $0.02423461$ & $0.02461756$ & $
 0.11987199$ & $0.16141739$\\

\hline
$\overline{E_{\mathbb{I}}}$   & $0.10525891$ & $0.00238599$ & $0.00572613$ & $0.01195496$ & $
 0.0960461 $ & $0.15864769$\\

\hline
$\tilde{E_{\mathbb{R}}}$  & $0.03512517$ & $0.02390339$ & $0.01056814$ & $0.00261824$ & $
 0.08628087$ & $0.11430801$\\

\hline

$\tilde{E_{\mathbb{I}}}$  & $0.0765563 $ & $0.00126931$ & $0.00069123$ & $0.02494961$ & $
 0.09446583$ & $0.0329332 $\\

\hline

$E_{\sigma\mathbb{R}}$  & $0.15996008$ & $0.05662694$ & $0.0327357 

## Estadísticas por amónico esférico

In [14]:
#Obtener el error por cada armónicos esférico
errorY = {}
j = 0
for l in range(nCubits + 1):
    for m in (0, l + 1):
        calculadoY["$Y_{" + str(l) + "}^{" + str(m) +  "}"] = []
        realY["$Y_{" + str(l) + "}^{" + str(m) +  "}"] = []
        errorY["$Y_{" + str(l) + "}^{" + str(m) +  "}"]
        for x in calculado.keys():
            calculadoY["$Y_{" + str(l) + "}^{" + str(m) +  "}"].append(calculado[x][j])
            realY["$Y_{" + str(l) + "}^{" + str(m) +  "}"].append(real[x][j])
            errorY["$Y_{" + str(l) + "}^{" + str(m) +  "}"].append(complex(abs(abs(c.real) - abs(r.real)), abs(abs(c.imag) - abs(r.imag))))


    arrTmp = []
    for c,r in zip(calculado[x], real[x]):
        arrTmp.append(complex(abs(abs(c.real) - abs(r.real)), abs(abs(c.imag) - abs(r.imag))))
    error[x] = np.array(arrTmp)


strListaElectrodosTituloTabla = (str(list(error.keys())).replace("'", "$").replace("[", "").replace("]", "").replace(",", " & "))
cabecera = "\\begin{figure}[h]\n"
cabecera += "\\centering\n"
cabecera += "\\begin{tabular}{|c|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|}\n"
cabecera += "\\hline\n"
cabecera += "& " + strListaElectrodosTituloTabla +"\\\\\n"
cabecera += "\\hline\n"
cabecera += "\\hline\n"
pie = "\\end{tabular}\n"
pie += "\\caption{Estadísticas de error por electrodo.}\n"
pie += "\\end{figure}\n"

print(cabecera)

E_max = {}
E_mean = {}
E_median = {}
E_std = {}
E_covIR = {}
#Calcular estadísticas
for x in error.keys():
        E_max[x] = max(error[x])
        E_mean[x] = np.mean(error[x])
        E_median[x] = np.median(error[x])
        E_std[x] = np.std(error[x])
        cov_mat = np.stack((error[x].real, error[x].imag), axis = 0)
        E_covIR[x] = np.cov(cov_mat)

strE_maxR = ("$E_{max\\mathbb{R}}$  & $" + np.array2string(np.array(list(E_max.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_meanR = ("$\\overline{E_{\\mathbb{R}}}$   & $" + np.array2string(np.array(list(E_mean.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_medianR = ("$\\tilde{E_{\\mathbb{R}}}$  & $" + np.array2string(np.array(list(E_median.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_stdR = ("$E_{\\sigma\\mathbb{R}}$  & $" + np.array2string(np.array(list(E_std.values())).real, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_maxI = ("$E_{max\\mathbb{I}}$  & $" + np.array2string(np.array(list(E_max.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_meanI = ("$\\overline{E_{\\mathbb{I}}}$   & $" + np.array2string(np.array(list(E_mean.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_medianI = ("$\\tilde{E_{\\mathbb{I}}}$  & $" + np.array2string(np.array(list(E_median.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")
strE_stdI = ("$E_{\\sigma\\mathbb{I}}$  & $" + np.array2string(np.array(list(E_std.values())).imag, precision=precision, separator='$ & $').replace("[", "").replace("]", "") + "$\\\\\n")

print(strE_maxR)
print("\\hline")
print(strE_maxI)
print("\\hline")
print(strE_meanR)
print("\\hline")
print(strE_meanI)
print("\\hline")
print(strE_medianR)
print("\\hline\n")
print(strE_medianI)
print("\\hline\n")
print(strE_stdR)
print("\\hline\n")
print(strE_stdI)
print("\\hline\n")
print(pie)

cabeceraCov = "\\begin{figure}[h]\n"
cabeceraCov += "\\centering\n"
print(cabeceraCov)
for x in E_covIR.keys():
        print("\\begin{subfigure}[t]{0.4\\textwidth}")
        print("\\begin{tabular}{|p{2cm}|p{2cm}|}")
        print("\\hline")
        print("\\multicolumn{2}{|c|}{$" + x + "$}\\\\")
        print("\\hline")
        print("$\\mathbb{R}$& $\mathbb{I}$ \\\\")
        print("\\hline\n\\hline")
        strTablaTmp = np.array2string(E_covIR[x])
        strTablaTmp = strTablaTmp.replace("[[", "$")
        strTablaTmp = strTablaTmp.replace("]]", "$\\\\\n")
        strTablaTmp = strTablaTmp.replace("]", "$\\\\")
        strTablaTmp = strTablaTmp.replace("[", "$")
        print(strTablaTmp)
        print("\\hline")
        print("\\end{tabular}")
        print("\\end{subfigure}")
print("\\end{figure}")




NameError: name 'calculadoY' is not defined